INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
    VALUES(1001,'USD','INR',65,'');

INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(1002,'EUR','INR',75,'');

INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(1001,'AUD','INR',100,'');

